//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AppEngine.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("AppEngine.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kontoinhaber.
        /// </summary>
        public static string AccountHolder {
            get {
                return ResourceManager.GetString("AccountHolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Buchhaltung.
        /// </summary>
        public static string Accounting {
            get {
                return ResourceManager.GetString("Accounting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mail-Import hinzufügen.
        /// </summary>
        public static string AddImap {
            get {
                return ResourceManager.GetString("AddImap", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Berechtigt.
        /// </summary>
        public static string Authorized {
            get {
                return ResourceManager.GetString("Authorized", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bankkonto hinterlegen, das für den QR-Code verwendet wird.
        /// </summary>
        public static string BankAccountConfigExplanation {
            get {
                return ResourceManager.GetString("BankAccountConfigExplanation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kontobewegungen.
        /// </summary>
        public static string BankStatements {
            get {
                return ResourceManager.GetString("BankStatements", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Abbrechen.
        /// </summary>
        public static string Cancel {
            get {
                return ResourceManager.GetString("Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Land (ISO2).
        /// </summary>
        public static string CountryCode {
            get {
                return ResourceManager.GetString("CountryCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hausnr..
        /// </summary>
        public static string HouseNo {
            get {
                return ResourceManager.GetString("HouseNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to IBAN.
        /// </summary>
        public static string Iban {
            get {
                return ResourceManager.GetString("Iban", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to IMAP-Postfächer konfigurieren, deren eingehende Mails fortlaufend importiert werden sollen..
        /// </summary>
        public static string ImapConfigExplanation {
            get {
                return ResourceManager.GetString("ImapConfigExplanation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mitteilung.
        /// </summary>
        public static string InsertRequestText {
            get {
                return ResourceManager.GetString("InsertRequestText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Eingeloggt als.
        /// </summary>
        public static string LoggedInAs {
            get {
                return ResourceManager.GetString("LoggedInAs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Einloggen.
        /// </summary>
        public static string Login {
            get {
                return ResourceManager.GetString("Login", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ausloggen.
        /// </summary>
        public static string Logout {
            get {
                return ResourceManager.GetString("Logout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mitglieder ohne Slack-Account.
        /// </summary>
        public static string MembersWithoutSlackAccount {
            get {
                return ResourceManager.GetString("MembersWithoutSlackAccount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OK.
        /// </summary>
        public static string OK {
            get {
                return ResourceManager.GetString("OK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Andere.
        /// </summary>
        public static string Other {
            get {
                return ResourceManager.GetString("Other", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to von {{debitor}}.
        /// </summary>
        public static string PaymentFrom {
            get {
                return ResourceManager.GetString("PaymentFrom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to an {{creditor}}.
        /// </summary>
        public static string PaymentTo {
            get {
                return ResourceManager.GetString("PaymentTo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PLZ.
        /// </summary>
        public static string Plz {
            get {
                return ResourceManager.GetString("Plz", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zugriff anfragen.
        /// </summary>
        public static string RequestAccess {
            get {
                return ResourceManager.GetString("RequestAccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rolle.
        /// </summary>
        public static string Role {
            get {
                return ResourceManager.GetString("Role", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Speichern.
        /// </summary>
        public static string Save {
            get {
                return ResourceManager.GetString("Save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Einstellungen.
        /// </summary>
        public static string Settings {
            get {
                return ResourceManager.GetString("Settings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Event vorbereiten.
        /// </summary>
        public static string Setup {
            get {
                return ResourceManager.GetString("Setup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Slack-Zuordnung.
        /// </summary>
        public static string SlackMatching {
            get {
                return ResourceManager.GetString("SlackMatching", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Strasse.
        /// </summary>
        public static string Street {
            get {
                return ResourceManager.GetString("Street", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Teammitglieder.
        /// </summary>
        public static string TeamMembers {
            get {
                return ResourceManager.GetString("TeamMembers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wohnort.
        /// </summary>
        public static string Town {
            get {
                return ResourceManager.GetString("Town", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nicht zuordenbare Slack-Accounts.
        /// </summary>
        public static string UnmatchedSlackAccount {
            get {
                return ResourceManager.GetString("UnmatchedSlackAccount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to bis {0}.
        /// </summary>
        public static string Until {
            get {
                return ResourceManager.GetString("Until", resourceCulture);
            }
        }
    }
}
